env:
  commonjs: true
  es6: true
  node: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  comma-dangle:
    - 2
    - only-multiline
  no-extra-parens:
    - 2
    - functions
  no-extra-semi: 2
  dot-location:
    - 2
    - property
  no-fallthrough: 2
  no-redeclare: 2
  no-self-assign: 2
  no-unused-labels: 2
  max-len:
    - error
    - code: 80
      comments: 120
      ignoreComments: true
      ignoreTemplateLiterals: true
      ignoreStrings: true
  no-multiple-empty-lines:
    - 2
    - max: 2
      maxEOF: 0
      maxBOF: 0
  no-tabs: 2
  no-trailing-spaces: 2
  quotes:
    - 2
    - single
    - avoid-escape
  semi: 2
  semi-spacing: 2
  space-before-blocks:
    - 2
    - always
  space-before-function-paren:
    - 2
    - named: never
      asyncArrow: always
  space-in-parens:
    - 2
    - never
  space-infix-ops: 2
  space-unary-ops: 2
  arrow-parens:
    - 2
    - always
  arrow-spacing:
    - 2
    - before: true
      after: true